#=======================================================================
#@V@:Note: File automatically generated by VIDE: (19:09:36 24 Feb 2000) (g++).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	g++

WRES	=	windres

HOMEV	=	c:\mingw32
VPATH	=	$(HOMEV)/include
oDir	=	../obj
Bin	=	../bin
Src	=	.
libDirs	=	-L$(HOMEV)/lib

incDirs	=	-I$(HOMEV)/include

LIBS	=	-s -mwindows -lV -lcomctl32
C_FLAGS	=	-O

SRCS	=\
	$(Src)/abtvdlg.cpp\
	$(Src)/cnewmdlg.cpp\
	$(Src)/cprojdlg.cpp\
	$(Src)/gdbdlg.cpp\
	$(Src)/jdbdlg.cpp\
	$(Src)/jprojdlg.cpp\
	$(Src)/mmaker.cpp\
	$(Src)/prefmdlg.cpp\
	$(Src)/vbaseci.cpp\
	$(Src)/vdbcmdw.cpp\
	$(Src)/vdbcnv.cpp\
	$(Src)/videapp.cpp\
	$(Src)/videcmdw.cpp\
	$(Src)/videcnv.cpp\
	$(Src)/videjava.cpp\
	$(Src)/videmake.cpp\
	$(Src)/vprefs.cpp\
	$(Src)/vrundlg.cpp\
	$(Src)/vseeci.cpp\
	$(Src)/vstdci.cpp\
	$(Src)/vvici.cpp\
	$(Src)/videlib.cpp

EXOBJS	=\
	$(oDir)/abtvdlg.o\
	$(oDir)/cnewmdlg.o\
	$(oDir)/cprojdlg.o\
	$(oDir)/gdbdlg.o\
	$(oDir)/jdbdlg.o\
	$(oDir)/jprojdlg.o\
	$(oDir)/mmaker.o\
	$(oDir)/prefmdlg.o\
	$(oDir)/vbaseci.o\
	$(oDir)/vdbcmdw.o\
	$(oDir)/vdbcnv.o\
	$(oDir)/videapp.o\
	$(oDir)/videcmdw.o\
	$(oDir)/videcnv.o\
	$(oDir)/videjava.o\
	$(oDir)/videmake.o\
	$(oDir)/vprefs.o\
	$(oDir)/vrundlg.o\
	$(oDir)/vseeci.o\
	$(oDir)/vstdci.o\
	$(oDir)/vvici.o\
	$(oDir)/videlib.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/vide.exe
ALLTGT	=	$(Bin)/vide.exe

# User defines:
# Resource file: vide.rc
EXOBJS += $(oDir)/vide.o

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------

# compile resource file
$(oDir)/vide.o:	$(Src)/vide.rc
	windres $(Src)/vide.rc $(oDir)/vide.o

#@# Dependency rules follow -----------------------------

$(Bin)/vide.exe: $(EXOBJS)
	$(CC) -o $(Bin)/vide.exe $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/abtvdlg.o: abtvdlg.cpp abtvdlg.h videapp.h videcmdw.h videmake.h \
 videjava.h jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h \
 gdbdlg.h jdbdlg.h videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/cnewmdlg.o: cnewmdlg.cpp cnewmdlg.h mmaker.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/cprojdlg.o: cprojdlg.cpp cprojdlg.h mmaker.h videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/gdbdlg.o: gdbdlg.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/jdbdlg.o: jdbdlg.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/jprojdlg.o: jprojdlg.cpp jprojdlg.h videjava.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/mmaker.o: mmaker.cpp mmaker.h videapp.h videcmdw.h videmake.h \
 videjava.h jprojdlg.h videcnv.h cprojdlg.h vdbcmdw.h gdbdlg.h \
 jdbdlg.h videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/prefmdlg.o: prefmdlg.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h prefmdlg.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vbaseci.o: vbaseci.cpp vbaseci.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vdbcmdw.o: vdbcmdw.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h vcmdcmds.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vdbcnv.o: vdbcnv.cpp vdbcnv.h videapp.h videcmdw.h videmake.h \
 videjava.h jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h \
 gdbdlg.h jdbdlg.h videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videapp.o: videapp.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h vprefs.h vrundlg.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videcmdw.o: videcmdw.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h vrundlg.h vseeci.h vbaseci.h vstdci.h vvici.h abtvdlg.h \
 prefmdlg.h cnewmdlg.h vcmdcmds.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videcnv.o: videcnv.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videjava.o: videjava.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videmake.o: videmake.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vprefs.o: vprefs.cpp vprefs.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vrundlg.o: vrundlg.cpp videapp.h videcmdw.h videmake.h videjava.h \
 jprojdlg.h videcnv.h cprojdlg.h mmaker.h vdbcmdw.h gdbdlg.h jdbdlg.h \
 videlib.h vrundlg.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vseeci.o: vseeci.cpp vseeci.h vbaseci.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vstdci.o: vstdci.cpp vstdci.h vbaseci.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vvici.o: vvici.cpp vvici.h vbaseci.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/videlib.o: videlib.cpp videlib.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
