//=======================================================================
//@V@:Note: This file generated by vgen V1.04 (10:25:37 22 Jun 1998).
//	gearapp.cpp:	Source for gearApp class
//=======================================================================

#include "gearapp.h"		// Header file

//=========================>>> gearApp::gearApp <<<==========================
  gearApp::gearApp(char* name, int sdi, int h, int w) : vApp(name, sdi, h, w)
  {
    // Constructor

   _gearCmdWin = 0;
  }

//=========================>>> gearApp::gearApp <<<==========================
  gearApp::~gearApp()
  {
    // Destructor
  }

//=====================>>> gearApp::NewAppWin <<<==========================
  vWindow* gearApp::NewAppWin(vWindow* win, char* name,
    int w, int h, vAppWinInfo* winInfo)
  {
    vAppWinInfo* awinfo = winInfo;
    char *appname = name;

    if (!*name)
      {
	 appname = "Gear Demo";		// Default name
      }
	
    UserDebug1(Build,"gearApp::NewAppWin(%s)\n",appname);

    // Create the first window using provided CmdWindow

    _gearCmdWin = (gearCmdWindow*) win;
    if (!_gearCmdWin)
      {
	_gearCmdWin = new gearCmdWindow(appname, w, h);
      }

    if (!awinfo)
	awinfo = new vAppWinInfo(appname);

    return vApp::NewAppWin(_gearCmdWin, appname, w, h, awinfo);
  }

//============================>>> gearApp::Exit <<<===========================
  void gearApp::Exit(void)
  {
    // This is called to close all windows.

    UserDebug(Build,"gearApp::Exit()\n");

    vApp::Exit();		// Default behavior
  }

//======================>>> gearApp::CloseAppWin <<<===========================
  int gearApp::CloseAppWin(vWindow* win)
  {
    // This will be called BEFORE a window has been unregistered or
    // closed.  Default behavior: unregister and close the window.

    UserDebug(Build,"gearApp::CloseAppWin()\n");

    return vApp::CloseAppWin(win);
  }

//=====================>>> gearApp::AppCommand <<<==============================
  void gearApp::AppCommand(vWindow* win, ItemVal id, ItemVal val, CmdType cType)
  {
    // Commands not processed by the window will be passed here

    UserDebug1(Build,"gearApp::AppCmd(ID: %d)\n",id);
    vApp::AppCommand(win, id, val, cType);
  }

//=========================>>> gearApp::KeyIn <<<==============================
  void gearApp::KeyIn(vWindow* win, vKey key, unsigned int shift)
  {
    // Key strokes not processed by the window will be passed here

    vApp::KeyIn(win, key, shift);
  }

//###########################################################################

  static gearApp gear_App("Gear Demo",1);	// The instance of the app

//============================>>> AppMain <<<==============================
  int AppMain(int argc, char** argv)
  {
    // Use AppMain to create the main window

    (void) theApp->NewAppWin(0, "Gear Demo", 300, 300);

    return 0;
  }
