//=======================================================================
//@V@:Note: This file generated by vgen V1.04 (10:58:59 22 Jun 1998).
//	bncapp.cpp:	Source for bncApp class
//=======================================================================

#include "bncapp.h"		// Header file

//=========================>>> bncApp::bncApp <<<==========================
  bncApp::bncApp(char* name, int sdi, int h, int w) : vApp(name, sdi, h, w)
  {
    // Constructor

   _bncCmdWin = 0;
  }

//=========================>>> bncApp::bncApp <<<==========================
  bncApp::~bncApp()
  {
    // Destructor
  }

//=====================>>> bncApp::NewAppWin <<<==========================
  vWindow* bncApp::NewAppWin(vWindow* win, char* name,
    int w, int h, vAppWinInfo* winInfo)
  {
    vAppWinInfo* awinfo = winInfo;
    char *appname = name;

    if (!*name)
      {
	 appname = "Bounce Demo";		// Default name
      }
	
    UserDebug1(Build,"bncApp::NewAppWin(%s)\n",appname);

    // Create the first window using provided CmdWindow

    _bncCmdWin = (bncCmdWindow*) win;
    if (!_bncCmdWin)
      {
	_bncCmdWin = new bncCmdWindow(appname, w, h);
      }

    if (!awinfo)
	awinfo = new vAppWinInfo(appname);

    return vApp::NewAppWin(_bncCmdWin, appname, w, h, awinfo);
  }

//============================>>> bncApp::Exit <<<===========================
  void bncApp::Exit(void)
  {
    // This is called to close all windows.

    UserDebug(Build,"bncApp::Exit()\n");

    vApp::Exit();		// Default behavior
  }

//======================>>> bncApp::CloseAppWin <<<===========================
  int bncApp::CloseAppWin(vWindow* win)
  {
    // This will be called BEFORE a window has been unregistered or
    // closed.  Default behavior: unregister and close the window.

    UserDebug(Build,"bncApp::CloseAppWin()\n");

    return vApp::CloseAppWin(win);
  }

//=====================>>> bncApp::AppCommand <<<==============================
  void bncApp::AppCommand(vWindow* win, ItemVal id, ItemVal val, CmdType cType)
  {
    // Commands not processed by the window will be passed here

    UserDebug1(Build,"bncApp::AppCmd(ID: %d)\n",id);
    vApp::AppCommand(win, id, val, cType);
  }

//=========================>>> bncApp::KeyIn <<<==============================
  void bncApp::KeyIn(vWindow* win, vKey key, unsigned int shift)
  {
    // Key strokes not processed by the window will be passed here

    vApp::KeyIn(win, key, shift);
  }

//###########################################################################

  static bncApp bnc_App("Bounce Demo",1);	// The instance of the app

//============================>>> AppMain <<<==============================
  int AppMain(int argc, char** argv)
  {
    // Use AppMain to create the main window

    (void) theApp->NewAppWin(0, "Bounce Demo", 300, 300);

    return 0;
  }
