//=======================================================================
//@V@:Note: This file generated by vappgen V 1.00.
//	vgcnv.cpp:	Source for vgTextCanvasPane class
//=======================================================================

#include "vgcnv.h"

//=================>>> vgTextCanvasPane::vgTextCanvasPane <<<================
  vgTextCanvasPane::vgTextCanvasPane()
  {
  }

//=================>>> vgTextCanvasPane::~vgTextCanvasPane <<<================
  vgTextCanvasPane::~vgTextCanvasPane()
  {
  }

//=====================>>> vgTextCanvasPane::HPage <<<========================
  void vgTextCanvasPane::HPage(int shown, int top)
  {
    vTextCanvasPane::HPage(shown, top);
  }

//=====================>>> vgTextCanvasPane::VPage <<<========================
  void vgTextCanvasPane::VPage(int shown, int top)
  {
    vTextCanvasPane::VPage(shown, top);
  }

//====================>>> vgTextCanvasPane::HScroll <<<======================
  void vgTextCanvasPane::HScroll(int step)
  {
    vTextCanvasPane::HScroll(step);
  }

//====================>>> vgTextCanvasPane::VScroll <<<======================
  void vgTextCanvasPane::VScroll(int step)
  {
    vTextCanvasPane::VScroll(step);
  }

//===================>>> vgTextCanvasPane::FontChanged <<<==================
  void vgTextCanvasPane::FontChanged(vFont& newFont)
  {
    vTextCanvasPane::FontChanged(newFont);
  }

//===================>>> vgTextCanvasPane::TextMouseDown <<<==================
  void vgTextCanvasPane::TextMouseDown(int row, int col, int button)
  {
    vTextCanvasPane::TextMouseDown(row,col,button);
  }

//======================>>> vgTextCanvasPane::TextMouseUp <<<==================
  void vgTextCanvasPane::TextMouseUp(int row, int col, int button)
  {
    vTextCanvasPane::TextMouseUp(row,col,button);
  }

//======================>>> vgTextCanvasPane::TextMouseMove <<<=================
  void vgTextCanvasPane::TextMouseMove(int row, int col, int button)
  {
    vTextCanvasPane::TextMouseMove(row,col,button);
  }

//=========================>>> vgTextCanvasPane::Redraw <<<======================
  void vgTextCanvasPane::Redraw(int x, int y, int width, int height)
  {
    vTextCanvasPane::Redraw(x,y,width,height);
  }

//======================>>> vgTextCanvasPane::ResizeText <<<======================
  void vgTextCanvasPane::ResizeText(const int rows, const int cols)
  {
    static int first = 1;
    if (first)
      {
	Clear();
	first = 0; DrawText("Welcome to the V Application Generator\n\n");
      }
    vTextCanvasPane::ResizeText(rows,cols);
  }
