//=======================================================================
//@V@:Note: This file generated by vappgen V 1.00.
 //	vgdlmdlg.h:	Header for vgdlgModalDialog class
//=======================================================================

#ifndef vgdlgMDLG_H
#define vgdlgMDLG_H

#include "vgdefs.h"
#include <v/vmodald.h>

    class vgdlgModalDialog : public vModalDialog
      {
      public:		//---------------------------------------- public
	vgdlgModalDialog(vBaseWindow*, char* title = "Generate Extra Dialog");
	virtual ~vgdlgModalDialog();		// Destructor
	virtual void DialogCommand(ItemVal,ItemVal,CmdType); // action selected
	virtual int vgdlgAction(char* msg, vgOptions& op);

      protected:	//--------------------------------------- protected

      private:		//--------------------------------------- private

      };
#endif
